### ISSUE TITLE
Changing line colour doesn’t work

### ISSUE THREAD

**Issue by a-sussy-impostor** [railmapgen/rmp#424] opened 2023-08-26 07:49 UTC
When I change the line colour (when drawing a line or configuring an interchange), there is a chance it wouldn’t work, the colour would not change.

Edit: The new line colour will flash a second when you reopen the GUI, but it will be back to the old colour again.

**Comment by thekingofcity** [comment] 2023-08-26 09:56
Hi, we are aware of a number of bug reports regarding the newly merged palette app clip. However, we still can not reproduce the problem, and thus is hard to debug. Feel free to detail the reproduction steps to help us :)

**Comment by a-sussy-impostor** [comment] 2023-08-27 07:55
It can happen at any time, but mostly after/during a configuration of an interchange station.

**Comment by a-sussy-impostor** [comment] 2023-08-27 13:22
Now I know, it’s caused by using a customized colour when configuring the interchange station’s line colour

**Comment by thekingofcity** [comment] 2023-08-27 14:32
Hi, we know the root cause of this problem and will provide a fix ASAP. Sorry for the inconvenience :)

**Comment by thekingofcity** [comment] 2023-08-29 06:46
Hi, it was fixed and will be released soon. Changes followed railmapgen/rmg#571 :)

**Closed** 2023-08-29 14:48 UTC
Labels: bug
